(defpackage #:org.shirakumo.fraf.manifolds
  (:use #:cl #:org.shirakumo.fraf.math)
  (:export
   #:vertex-array
   #:face-array
   #:vertex
   #:face
   #:u32
   #:f32
   #:f64
   #:ensure-u32
   #:ensure-f32
   #:ensure-f64
   #:u32*
   #:f32*
   #:f64*)
  (:export
   #:do-faces
   #:vertex-adjacency-list
   #:face-adjacency-list
   #:half-edge-list
   #:edge-list
   #:boundary-list
   #:v
   #:face-normal
   #:face-normals
   #:face-area
   #:surface-area
   #:boundary-length
   #:centroid
   #:convex-volume
   #:closest-point-on-triangle
   #:ray-triangle
   #:face-in-volume-p
   #:faces-in-volume
   #:bounding-box
   #:vertex-faces
   #:2-manifold-p
   #:separate-meshes
   #:normalize))
